version: 0.0
os: linux
files:
   - source: /
     destination: /var/www
permissions:
   - object: /var/www
     pattern: "**"
     owner: apache
     group: apache
     mode: 755
     type:
       - file
hooks:
   BeforeInstall:
    - location: scripts/installapache.sh
      runas: ubuntu
    - location: scripts/startapache.sh
      runas: ubuntu
   AfterInstall:
    - location: scripts/restartapache.sh
      runas: ubuntu
